services:
  app:
    container_name: ${APP_NAME}
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "6060:6060"
    networks:
      - api
    depends_on:
      - db
  db:
    container_name: ${APP_NAME}-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    volumes:
      - ./vopi-chat-drawio_2025-08-16T18_46_32.846Z_postgres.sql:/docker-entrypoint-initdb.d/vopi-chat-drawio_2025-08-16T18_46_32.846Z_postgres.sql
    ports:
      - "5332:5432"
    networks:
      - api

networks:
  api:
    driver: bridge
