auth_enabled: false

limits_config:
    allow_structured_metadata: true
    volume_enabled: true

server:
    http_listen_port: 3100

common:
    instance_addr: 127.0.0.1
    path_prefix: /loki
    storage:
        filesystem:
            chunks_directory: /loki/chunks
            rules_directory: /loki/rules
    replication_factor: 1
    ring:
        kvstore:
            store: inmemory

query_range:
    results_cache:
        cache:
            embedded_cache:
                enabled: true
                max_size_mb: 100

schema_config:
    configs:
        - from: 2020-05-15
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
              prefix: index_
              period: 24h

storage_config:
    tsdb_shipper:
        active_index_directory: /tmp/loki/index
        cache_location: /tmp/loki/index_cache
    filesystem:
        directory: /tmp/loki/chunks

pattern_ingester:
    enabled: false
