receivers:
    otlp:
        protocols:
            grpc:
                endpoint: 0.0.0.0:4317
            http:
                endpoint: 0.0.0.0:4318

    prometheus:
        config:
            scrape_configs:
                - job_name: "otel-collector"
                  scrape_interval: 10s
                  static_configs:
                      - targets: ["0.0.0.0:8888"]

processors:
    batch:

    resource:
        attributes:
            - action: insert
              key: loki.resource.labels
              value: service.name, service.namespace
            - action: insert
              key: loki.format
              value: json

exporters:
    debug:
        verbosity: detailed

    prometheus:
        endpoint: "0.0.0.0:8889"
        const_labels:
            label: "prometheus"
        resource_to_telemetry_conversion:
            enabled: true
        enable_open_metrics: true

    otlp:
        endpoint: tempo:4317
        tls:
            insecure: true
    otlp/jaeger:
        endpoint: jaeger:4317
        tls:
            insecure: true

    otlphttp/logs:
        endpoint: "http://loki:3100/otlp"
        tls:
            insecure: true

service:
    pipelines:
        traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp/jaeger]
        # metrics:
        #     receivers: [otlp, prometheus]
        #     processors: [batch]
        #     exporters: [prometheus]
        # logs:
        #     receivers: [otlp]
        #     processors: [batch]
        #     exporters: [otlphttp/logs]
